name: saudefx
version: '0.1.0'
summary: Indicadores de saúde
description: |
  Projeto feito em Java/JavaFX visando demostrar alguns indicadores de saúde.
base: core18
grade: stable
confinement: strict
apps:
  saudefx:
    
    command: desktop-launch java --module-path=$PATH_TO_FX --add-modules=javafx.controls,javafx.fxml -Dprism.fontsdir=$SNAP/usr/share/fonts/truetype -Dprism.useFontConfig=true -cp $SNAP/jar/SaudeFX-0.1-SNAPSHOT.jar br.com.saudefx.App
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-11-openjdk-amd64
      PATH: $JAVA_HOME/jre/bin:$PATH
      PATH_TO_FX: $SNAP/javafx-sdk-11.0.2/lib
    
    plugs:
      - x11
      # - network
      # - network-bind
      # - desktop
      # - desktop-legacy
      # - wayland
      # - home
      # - gsettings
      # - camera
      # - opengl

parts:
  saudefx:
    plugin: maven 
    source: .
    maven-options: [compile]
    build-packages: [openjdk-11-jdk]
    stage-packages: 
      - openjdk-11-jre
      - ttf-mscorefonts-installer
      - fonts-3270
      - fonts-adf-accanthis
      - fonts-fanwood
      - fonts-ebgaramond-extra
      - x11-utils
      - libfontconfig1
      - libfontenc1
      - mesa-utils
      - libwebkit2gtk-4.0-37
    after: [desktop-gtk3]

  javafx-11:
    plugin: dump 
    source: .
    stage: 
      - javafx-sdk-11.0.2
    stage-packages:
      - libcanberra-gtk-module
      - openjfx

    

  # desktop-gtk3:
  #   source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
  #   source-subdir: gtk
  #   plugin: make
  #   make-parameters: ["FLAVOR=gtk3"]
  #   build-packages:
  #     - libgtk-3-dev
  #   stage-packages:
  #     - libxkbcommon0  # XKB_CONFIG_ROOT
  #     - ttf-ubuntu-font-family
  #     - dmz-cursor-theme
  #     - light-themes
  #     - adwaita-icon-theme
  #     - gnome-themes-standard
  #     - shared-mime-info
  #     - libgtk-3-0
  #     - libgdk-pixbuf2.0-0
  #     - libglib2.0-bin
  #     - libgtk-3-bin
  #     - unity-gtk3-module
  #     - libappindicator3-1
  #     - locales-all
  #     - xdg-user-dirs
  #     - ibus-gtk3
  #     - libibus-1.0-5



     
