name: saudefx
version: '0.2.0'
summary: Indicadores de saúde
description: |
  Projeto feito em Java/JavaFX visando demostrar alguns indicadores de saúde.
base: core18
grade: stable
confinement: strict

apps:
  saudefx:
    command: desktop-launch java --module-path=$PATH_TO_FX --add-modules=javafx.controls,javafx.fxml,com.jfoenix --add-exports javfx.controls/com.sun.javafx.scene.control=com.jfoenix --add-exports javafx.controls/com.sun.javafx.scene.control.behavior=com.jfoenix -cp $SNAP/shade/SaudeFX.jar br.com.saudefx.App
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-11-openjdk-amd64
      PATH: $JAVA_HOME/jre/bin:$PATH
      PATH_TO_FX: $SNAP/javafx-sdk-11.0.2/lib
    plugs:
      - desktop
      - unity7

parts:
  saudefx:
    plugin: maven 
    source: .
    maven-options: [compile]
    build-packages: [openjdk-11-jdk]
    stage-packages: 
      - openjdk-11-jre
    after: [desktop-glib-only]


  javafx-11:
    plugin: dump 
    source: snap/local- wayland
    stage: 
      - javafx-sdk-11.0.2
      - saudefx.png
    stage-packages:
      - openjfx
