name: saudefx
version: '0.2.0'
summary: Indicadores de saúde
description: |
  Projeto feito em Java/JavaFX visando demostrar alguns indicadores de saúde.
base: core18
grade: stable
confinement: strict

parts:
  saudefx:
    plugin: maven 
    source: .
    maven-options: [install]

  javafx-11:
    plugin: dump 
    source: snap/local
    stage: 
      - javafx-sdk-11.0.2
      - saudefx.png
      - saudefx.sh

apps:
  saudefx:
    command: desktop-launch $SNAP/saudefx.sh
    extensions: [gnome-3-28]
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-11-openjdk-amd64
      PATH: $JAVA_HOME/jre/bin:$PATH
      PATH_TO_FX: $SNAP/javafx-sdk-11.0.2/lib
    plugs:
      - desktop
      - unity7
      - home
      - network
      - cups-control
